version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - frontend-backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - frontend-backend
      - backend-mysql

  mysql:
    build:
      context: .
      dockerfile: mysql/Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-mysql

networks:
  frontend-backend:
  backend-mysql:

volumes:
  mysql-data:
    driver: dump
